# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, verbose_name='申请部门')),
                ('the_company', models.CharField(max_length=100, null=True, verbose_name='公司')),
            ],
            options={
                'verbose_name': '猫号部门信息表',
                'verbose_name_plural': '猫号部门信息表',
            },
        ),
        migrations.CreateModel(
            name='domain_filed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed1', models.CharField(max_length=100, null=True)),
                ('filed2', models.CharField(max_length=100, null=True)),
                ('filed3', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=10, verbose_name='验证码类型')),
                ('send_time', models.DateTimeField(verbose_name='发送时间')),
            ],
        ),
        migrations.CreateModel(
            name='filed1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': '域名字段1表',
                'verbose_name_plural': '域名字段1表',
            },
        ),
        migrations.CreateModel(
            name='filed2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': '域名字段2表',
                'verbose_name_plural': '域名字段2表',
            },
        ),
        migrations.CreateModel(
            name='filed3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': '域名字段3表',
                'verbose_name_plural': '域名字段3表',
            },
        ),
        migrations.CreateModel(
            name='mail_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_address', models.CharField(max_length=100, unique=True, verbose_name='邮件地址')),
                ('mail_name', models.CharField(max_length=100, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '邮件接收人表',
                'verbose_name_plural': '邮件接收人表',
            },
        ),
        migrations.CreateModel(
            name='maohao_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('maohao', models.CharField(max_length=100, verbose_name='猫号')),
                ('phone', models.CharField(max_length=100, verbose_name='注册手机号')),
                ('times', models.CharField(max_length=100, verbose_name='注册时间')),
                ('use', models.CharField(max_length=100, null=True, verbose_name='使用情况说明用途')),
                ('DepartmenT', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Department', verbose_name='申请部门')),
            ],
            options={
                'verbose_name': '猫号信息表',
                'verbose_name_plural': '猫号信息表',
            },
        ),
        migrations.CreateModel(
            name='registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, verbose_name='域名')),
                ('ip', models.CharField(max_length=30, null=True, verbose_name='要解析到的IP地址')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='申请人')),
                ('department', models.CharField(max_length=100, null=True, verbose_name='申请部门')),
                ('use', models.CharField(max_length=100, null=True, verbose_name='域名用途')),
                ('https', models.CharField(max_length=100, null=True, verbose_name='是否需要https')),
                ('Review_status', models.CharField(max_length=100, null=True, verbose_name='审核状态')),
                ('RecordId', models.CharField(max_length=100, null=True, verbose_name='解析记录的ID')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
            ],
            options={
                'verbose_name': '域名信息表',
                'verbose_name_plural': '域名信息表',
            },
        ),
        migrations.CreateModel(
            name='userpro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
