# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userpro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='申请部门'),
        ),
        migrations.AddField(
            model_name='registered',
            name='https',
            field=models.CharField(max_length=100, null=True, verbose_name='是否需要https'),
        ),
        migrations.AddField(
            model_name='registered',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='registered',
            name='use',
            field=models.CharField(max_length=100, null=True, verbose_name='域名用途'),
        ),
    ]
