# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170316_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='domain_filed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed1', models.CharField(max_length=100)),
                ('filed2', models.CharField(max_length=100)),
                ('filed3', models.CharField(max_length=100)),
            ],
        ),
    ]
