# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_registered_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='ip',
            field=models.CharField(max_length=30, null=True, verbose_name='要解析到的IP地址'),
        ),
        migrations.AlterField(
            model_name='registered',
            name='domain',
            field=models.CharField(max_length=100, verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='registered',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, verbose_name='时间'),
        ),
    ]
