# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20170807_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='RecordId',
            field=models.CharField(max_length=100, null=True, verbose_name='解析记录的ID'),
        ),
    ]
