# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_registered_recordid'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_address', models.CharField(max_length=100, unique=True, verbose_name='邮件地址')),
                ('mail_name', models.CharField(max_length=100, verbose_name='姓名')),
            ],
        ),
    ]
