# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20171102_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, verbose_name='申请部门')),
            ],
        ),
        migrations.AlterField(
            model_name='maohao_info',
            name='use',
            field=models.CharField(max_length=100, null=True, verbose_name='使用情况说明用途'),
        ),
        migrations.AddField(
            model_name='maohao_info',
            name='DepartmenT',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Department'),
        ),
    ]
