# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20171106_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maohao_info',
            name='department',
        ),
    ]
