# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_remove_maohao_info_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maohao_info',
            name='DepartmenT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Department'),
        ),
    ]
