# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_auto_20171106_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maohao_info',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='注册手机号'),
        ),
        migrations.AlterField(
            model_name='maohao_info',
            name='times',
            field=models.CharField(max_length=100, verbose_name='注册时间'),
        ),
    ]
