# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(verbose_name='发送时间'),
        ),
    ]
